### ISSUE TITLE
2022-07-30 21:21:32.046 [Thread-0] DEBUG i.n.u.internal.NativeLibraryLoader - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.

### ISSUE THREAD

**Issue by y-a-n-n** [y-a-n-n/laterball#4]
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1124)
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)
        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
        at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:250)
        at io.netty.channel.epoll.Native.<clinit>(Native.java:69)
        at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create(NettyApplicationEngine.kt:212)
        at io.ktor.server.netty.NettyApplicationEngine$workerEventGroup$2.invoke(NettyApplicationEngine.kt:89)
        at io.ktor.server.netty.NettyApplicationEngine$workerEventGroup$2.invoke(NettyApplicationEngine.kt:26)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.ktor.server.netty.NettyApplicationEngine.getWorkerEventGroup(NettyApplicationEngine.kt)
        at io.ktor.server.netty.NettyApplicationEngine.access$getWorkerEventGroup$p(NettyApplicationEngine.kt:26)
        at io.ktor.server.netty.NettyApplicationEngine$engineDispatcherWithShutdown$2.invoke(NettyApplicationEngine.kt:109)
        at io.ktor.server.netty.NettyApplicationEngine$engineDispatcherWithShutdown$2.invoke(NettyApplicationEngine.kt:26)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.ktor.server.netty.NettyApplicationEngine.getEngineDispatcherWithShutdown(NettyApplicationEngine.kt)
        at io.ktor.server.netty.NettyApplicationEngine.stop(NettyApplicationEngine.kt:167)
        at io.ktor.server.engine.ApplicationEngineJvmKt.stop(ApplicationEngineJvm.kt:18)
        at io.ktor.server.netty.EngineMain$main$1.invoke(EngineMain.kt:24)
        at io.ktor.server.netty.EngineMain$main$1.invoke(EngineMain.kt:14)
        at io.ktor.server.engine.ShutdownHook.run(ShutdownHook.kt:39)
2022-07-30 21:21:32.048 [Thread-0] DEBUG i.n.u.internal.NativeLibraryLoader - netty_transport_native_epoll_x86_64 cannot be loaded from java.library.path, now trying export to -Dio.netty.native.workdir: /tmp
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1124)
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
        at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:250)
        at io.netty.channel.epoll.Native.<clinit>(Native.java:69)
        at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create(NettyApplicationEngine.kt:212)
        at io.ktor.server.netty.NettyApplicationEngine$workerEventGroup$2.invoke(NettyApplicationEngine.kt:89)
        at io.ktor.server.netty.NettyApplicationEngine$workerEventGroup$2.invoke(NettyApplicationEngine.kt:26)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.ktor.server.netty.NettyApplicationEngine.getWorkerEventGroup(NettyApplicationEngine.kt)
        at io.ktor.server.netty.NettyApplicationEngine.access$getWorkerEventGroup$p(NettyApplicationEngine.kt:26)
        at io.ktor.server.netty.NettyApplicationEngine$engineDispatcherWithShutdown$2.invoke(NettyApplicationEngine.kt:109)
        at io.ktor.server.netty.NettyApplicationEngine$engineDispatcherWithShutdown$2.invoke(NettyApplicationEngine.kt:26)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.ktor.server.netty.NettyApplicationEngine.getEngineDispatcherWithShutdown(NettyApplicationEngine.kt)
        at io.ktor.server.netty.NettyApplicationEngine.stop(NettyApplicationEngine.kt:167)
        at io.ktor.server.engine.ApplicationEngineJvmKt.stop(ApplicationEngineJvm.kt:18)
        at io.ktor.server.netty.EngineMain$main$1.invoke(EngineMain.kt:24)
        at io.ktor.server.netty.EngineMain$main$1.invoke(EngineMain.kt:14)
        at io.ktor.server.engine.ShutdownHook.run(ShutdownHook.kt:39)
        Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
                at java.lang.Runtime.loadLibrary0(Runtime.java:871)
                at java.lang.System.loadLibrary(System.java:1124)
                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)
                at java.security.AccessController.doPrivileged(Native Method)
                at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)
                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
                ... 19 common frames omitted

**Comment by y-a-n-n** [comment]
Closing: https://github.com/netty/netty/issues/7319
